slimphp/Slim-Skeleton

public/index.php
some assets like font-awesome by default add a get parameter with the version to their static files to improve caching. this change allows those files to be served directly as well
=> updated static file handling for built-in PHP server

src/settings.php
False is the correct setting, but it defaults to true for legacy reasons. When set to false, we let the web browser set the content length header and so tools like RunScope work.
=> Set addContentLengthHeader to false

docker-compose.yml, src/settings.php
* Added docker-compose.yml with default runtime, php:7-alpine
* Allowing logging to stdout to be toggled with environment switch: docker.
This better suits docker workflow and allows docker-compose to capture the logging to the consol
=> Adding docker with docker-compose support

composer.json
If you bind to 0.0.0.0, then it's world accessible, so better practice is to just bind locally.
Closes https://github.com/slimphp/Slim/issues/2074.
=> Bind to localhost

README.md
Include the cd command to change into the application directory. Mention the application directory explicitly. Avoids some early frustrations for newbie users.
=> Improve REAME.md for dummy users

composer.json
We can remove `public` from running the built-in server in composer.json
=> Remove public from running built-in server as this is not necessary

docker-compose.yml
Resolves #84 where some Docker users are running into issues with the internal PHP server not serving the site properly
=> 🚑 Drop index.php from php internal server command

tests/Functional/HomepageTest.php
When running phpunit just after the install of Slim-Skeleton I'm receiving some warnings from phpunit about the methods `assertContains` and `assertNotContains` that will be deprecated in PHPUnit 9.
Issue:
This PR aims to fix the issue with those methods.
Fix:
=> Fix deprecated methods on HomepageTest

src/Application/Handlers/HttpErrorHandler.php
Errors are currently being served with a content type of text/html.
=> Ensure json content type for error responses

.gitignore, app/dependencies.php, app/repositories.php, app/settings.php, public/index.php, tests/TestCase.php
Addresses #112.
* Uses ContainerBuilder instead of instantiating Container instance directly
* Refactors settings, dependencies and repositories callbacks to set definitions on ContainerBuilder
* Conditionally enables container compilation
A couple of questions:
https://github.com/ssnepenthe/Slim-Skeleton/blob/f5b5fcf201fb0840820117927105b394a06e53e7/public/index.php#L16
What should the condition for enabling container compilation be? I tend to do something like `'development' !== getenv('APP_ENVIRONMENT')`, but for this PR I tried to stick to the behavior already seen for the `displayErrorDetails` setting and allow individual users to define their own condition.
https://github.com/ssnepenthe/Slim-Skeleton/blob/f5b5fcf201fb0840820117927105b394a06e53e7/public/index.php#L17
Where should the …
=> Use PHP-DI ContainerBuilder over direct Container manipulation

app/dependencies.php
Sorry - I should have included this in the previous PR.
From the [docs](http://php-di.org/doc/php-definitions.html#factories):
> When injecting the container, you should type-hint against the interface Psr\Container\ContainerInterface instead of the implementation DI\Container.
=> Change PHP-DI factory type hints from Container to ContainerInterface

src/Application/ResponseEmitter/ResponseEmitter.php
I was getting the following error
```
{
"statusCode": 500,
"error": {
"type": "SERVER_ERROR",
"description": "ERROR: ob_clean(): failed to delete buffer. No buffer to delete on line 28 in file \/var\/www\/src\/Application\/ResponseEmitter\/ResponseEmitter.php."
}
}
```
Which I thought was strange. This PR fixes it though.
=> FIX check if there is a buffer before cleaning it.

app/routes.php
DI container instance accessible inside of the Closure via the `$this` keyword
=> remove unused $app->getContainer() in routes

.gitignore, var/cache/.gitignore
so user doesn't need to manually create `var/cache` directory when activating cache, eg, activating cache like in https://github.com/slimphp/Slim-Skeleton/blob/master/public/index.php#L17
=> create var/cache directory with .gitignore in it

app/routes.php
As pointed out in #140 the pre-flight requests fail as there's no route to handle the `OPTIONS` method. The `ResponseEmitter` already has the CORS headers https://github.com/slimphp/Slim-Skeleton/blob/master/src/Application/ResponseEmitter/ResponseEmitter.php#L19
=> Add CORS OPTIONS handler

tests/Infrastructure/Persistence/User/InMemoryUserRepositoryTest.php
Add unit test to cover findAll function, for the case when calling the InMemoryUserRepository constructor passing $users with null value.
=> Add new test to find all users by default

app/routes.php
Previous will not match to the root of a domain, since the pattern is
configured to look for one or more characters after the /, whereas it
should be zero or more.
Example of previous, broken regex: https://regex101.com/r/F7HTMT/1
Example of fixed, new regex: https://regex101.com/r/unu0lu/1
=> fix: correct cors route regex

.gitignore, src/Application/Actions/Action.php, tests/Application/Actions/ActionTest.php
Currently when we pass a status code to the constructor of the ActionPayload class it is only used as a field in our json response. If we don't provide an error to the constructor, the HTTP code is always 200. It doesn't work for all scenarios. In some cases I would return the code 202 and provide information on when the action will be fully completed.
=> Use the code passed to ActionPayload for the HTTP status code

composer.json, phpstan.neon.dist
This PR
Related to #165.
💁‍♂️ This should help with https://github.com/Jan0707/phpstan-prophecy/issues/179 and upgrading https://github.com/Jan0707/phpstan-prophecy/compare/0.6.2...0.8.0!
=> Enhancement: Require and use phpstan/extension-installer

composer.json
Currently when installing via composer on a PHP 8 machine, this throws an error due to the PHP 7 requirement currently in place.
=> Allow PHP 8 usage

.htaccess, public/.htaccess
The following error occurred in .htaccess on Apache. This pull request will fix that error.
Apache version: 2.4.48 (Debian) (Docker image php:7.4-apache)
- error: `Invalid command '+Options', perhaps misspelled or defined by a module not included in the server configuration`
-> "+Options" is a mistake of "Options"
- error: `Illegal option \xe2\x80\x93Indexes`
-> "–" is en dash(U+2013), not ascii
=> Fix .htaccess syntax error in Apache

src/Application/Actions/ActionError.php
Please see this issue for context:
https://github.com/slimphp/Slim-Skeleton/issues/289
=> Fix optional type $description in ActionError can not be set to `null`

src/Application/Actions/User/ViewUserAction.php
This is a PR for issue #320.
Switch to a non-deprecated string interpolation syntax for PHP 8.2.
=> Fix deprecated string interpolation syntax

docker-compose.yml
You get an error if you try to run the skeleton app under php 7. Using `php:8-alpine` fixes it.
=> update php image version to 8-alpine

.htaccess, public/.htaccess
Related to issue #313. Removed old 2.2. syntax and updated with the equivalent 2.4. syntax.
=> Updated syntax to apache 2.4. version.

src/Application/Handlers/ShutdownHandler.php
Hi guys, thanks for this awesome micro framework.
I made this little refactor using early return to reduce cyclomatic complexity in this class. In my personal project I made unit test for this class, if you want too, feel free to talk me that I provide a test here too.
=> Little refactor using early return
